import { SpinalGraph, SpinalContext, SpinalNode } from 'spinal-env-viewer-graph-service';
import { IProfile, IProfileRes, IBosAuth, IPortofolioAuth, IPortofolioAuthRes, IBosAuthRes } from '../interfaces';
export declare class AppProfileService {
    private static instance;
    context: SpinalContext;
    private constructor();
    static getInstance(): AppProfileService;
    init(): Promise<SpinalContext>;
    createAppProfile(appProfile: IProfile): Promise<IProfileRes>;
    getAppProfile(appProfile: string | SpinalNode): Promise<IProfileRes>;
    updateAppProfile(appProfileId: string, appProfile: IProfile): Promise<IProfileRes>;
    getAllAppProfile(): Promise<IProfileRes[]>;
    getAllAppProfileNodes(): Promise<SpinalNode<import("spinal-core-connectorjs").Model>[]>;
    deleteAppProfile(appProfileId: string): Promise<string>;
    authorizePortofolio(profile: string | SpinalNode, portofolioId: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessPortofolio(profile: string | SpinalNode, portofolioId: string | string[]): Promise<void[]>;
    authorizeToAccessPortofolioApp(profile: string | SpinalNode, data: IPortofolioAuth | IPortofolioAuth[]): Promise<IPortofolioAuthRes[]>;
    unauthorizeToAccessPortofolioApp(profile: string | SpinalNode, data: IPortofolioAuth | IPortofolioAuth[]): Promise<SpinalNode[][]>;
    getAuthorizedPortofolio(profile: string | SpinalNode): Promise<SpinalNode[]>;
    getAuthorizedPortofolioApp(profile: string | SpinalNode, portofolioId: string): Promise<SpinalNode[]>;
    getPortofolioAuthStructure(profile: string | SpinalNode): Promise<IPortofolioAuthRes[]>;
    authorizeToAccessApis(appProfile: string | SpinalNode, apisIds?: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessApis(appProfile: string | SpinalNode, apisIds?: string | string[]): Promise<string[]>;
    getAuthorizedApis(appProfile: string | SpinalNode): Promise<SpinalNode[]>;
    authorizeToAccessBos(profile: SpinalNode | string, BosId: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessBos(profile: SpinalNode | string, BosId: string | string[]): Promise<void[]>;
    authorizeToAccessBosApp(profile: SpinalNode | string, data: IBosAuth | IBosAuth[]): Promise<IBosAuthRes[]>;
    unauthorizeToAccessBosApp(profile: SpinalNode | string, data: IBosAuth | IBosAuth[]): Promise<SpinalNode[][]>;
    getAuthorizedBos(profile: SpinalNode | string): Promise<SpinalNode[]>;
    getAuthorizedBosApp(profile: SpinalNode | string, bosId: string): Promise<SpinalNode[]>;
    getBosAuthStructure(profile: string | SpinalNode): Promise<IBosAuthRes[]>;
    _getAppProfileNodeGraph(profileId: string): Promise<SpinalGraph | void>;
    private _findChildInContext;
    private _addProfileToGraph;
    private _createAppProfileNode;
    private _getAppProfileNode;
    private _renameProfile;
    private _unauthorizeOnEdit;
    private _authorizeOnEdit;
}
