import { SpinalGraph, SpinalContext, SpinalNode } from 'spinal-env-viewer-graph-service';
import { IBosAuth, IPortofolioAuth, IProfile, IProfileRes, IPortofolioAuthRes, IBosAuthRes } from '../interfaces';
export declare class UserProfileService {
    private static instance;
    context: SpinalContext;
    private constructor();
    static getInstance(): UserProfileService;
    init(): Promise<SpinalContext>;
    createUserProfile(userProfile: IProfile): Promise<IProfileRes>;
    getUserProfile(userProfile: string | SpinalNode): Promise<IProfileRes>;
    updateUserProfile(userProfileId: string, userProfile: IProfile): Promise<IProfileRes>;
    getAllUserProfile(): Promise<IProfileRes[]>;
    getAllUserProfilesNodes(): Promise<SpinalNode[]>;
    deleteUserProfile(userProfileId: string): Promise<string>;
    authorizePortofolio(profile: string | SpinalNode, portofolioId: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessPortofolio(profile: string | SpinalNode, portofolioId: string | string[]): Promise<void[]>;
    authorizeToAccessPortofolioApp(profile: string | SpinalNode, data: IPortofolioAuth | IPortofolioAuth[]): Promise<IPortofolioAuthRes[]>;
    unauthorizeToAccessPortofolioApp(profile: string | SpinalNode, data: IPortofolioAuth | IPortofolioAuth[]): Promise<SpinalNode[][]>;
    getAuthorizedPortofolio(profile: string | SpinalNode): Promise<SpinalNode[]>;
    getAuthorizedPortofolioApp(profile: string | SpinalNode, portofolioId: string): Promise<SpinalNode[]>;
    getPortofolioAuthStructure(profile: string | SpinalNode): Promise<IPortofolioAuthRes[]>;
    authorizeToAccessApis(userProfile: string | SpinalNode, apisIds?: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessApis(userProfile: string | SpinalNode, apisIds?: string | string[]): Promise<string[]>;
    getAuthorizedApis(userProfile: string | SpinalNode): Promise<SpinalNode[]>;
    authorizeToAccessBos(profile: SpinalNode | string, BosId: string | string[]): Promise<SpinalNode[]>;
    unauthorizeToAccessBos(profile: SpinalNode | string, BosId: string | string[]): Promise<void[]>;
    authorizeToAccessBosApp(profile: SpinalNode | string, data: IBosAuth | IBosAuth[]): Promise<IBosAuthRes[]>;
    unauthorizeToAccessBosApp(profile: SpinalNode | string, data: IBosAuth | IBosAuth[]): Promise<SpinalNode[][]>;
    getAuthorizedBos(profile: SpinalNode | string): Promise<SpinalNode[]>;
    getAuthorizedBosApp(profile: SpinalNode | string, bosId: string): Promise<SpinalNode[]>;
    getBosAuthStructure(profile: string | SpinalNode): Promise<IBosAuthRes[]>;
    _getUserProfileNodeGraph(profileId: string): Promise<SpinalGraph | void>;
    private _findChildInContext;
    private _addProfileToGraph;
    private _createUserProfileNode;
    private _getUserProfileNode;
    private _renameProfile;
    private _unauthorizeOnEdit;
    private _authorizeOnEdit;
}
