import { IBosAuth, IPortofolioAuth, IProfile, IProfileRes, IPortofolioAuthRes, IBosAuthRes, IPortofolioData, IBosData, IProfileData } from "../interfaces";
import { SpinalContext, SpinalGraph, SpinalNode } from 'spinal-env-viewer-graph-service';
export declare function _formatProfile(data: IProfileRes): IProfileData;
export declare function _formatPortofolioAuthRes(data: IPortofolioAuthRes): IPortofolioData;
export declare function _formatBosAuthRes(data: IBosAuthRes): IBosData;
export declare function _getNodeListInfo(nodes?: SpinalNode[]): any[];
export declare function _formatProfileKeys(profile: IProfile): IProfile;
export declare function formatAndMergeBosAuthorization(itemsToAuthorize: IBosAuth[]): IBosAuth[];
export declare function formatAndMergePortofolioAuthorization(itemsToAuthorize: IPortofolioAuth[], isCompatibleWithBosC: boolean): IPortofolioAuth[];
export declare function _findChildInContext(startNode: SpinalNode, nodeIdOrName: string, context: SpinalContext): Promise<SpinalNode>;
export declare function _createProfileNode(profile: IProfile): Promise<SpinalNode>;
export declare function _getProfileNode(profileId: string, context: SpinalContext): Promise<SpinalNode>;
export declare function _renameProfile(node: SpinalNode, newName: string): void;
export declare function _getProfileNodeGraph(profileId: string, context: SpinalContext): Promise<SpinalGraph | void>;
